workflows:
  ios-build:
    name: iOS Build (Unsigned)
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate iOS files manually
        script: | 
          flutter config --enable-ios
          flutter create . --platforms ios
      - name: Install dependencies
        script: | 
          flutter packages pub get
      - name: Install Pods
        script: |
          find . -maxdepth 1 -type d \( -name ios \) -exec bash -c "cd '{}' && pod install" \;
      - name: Build iOS (Unsigned)
        script: | 
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app

  android-build:
    name: Android Build (APK)
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
