workflows:
  ios-workflow:
    name: iOS Build
    scripts:
      - name: Generate iOS files manually
        script: | 
          # Ensure we are in the project root and create iOS files
          cd . 
          flutter create . --platforms ios
      - name: Install Pods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: | 
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - user_email@example.com
